; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:custom_atmega328p]
platform = atmelavr
board = ATmega328
framework = arduino

; Trỏ đến thư viện MiniCore
board_build.core = minicore

; Cấu hình phần cứng: Báo cho PlatformIO biết ta dùng dao động nội 8MHz
board_build.f_cpu = 8000000L
board_hardware.oscillator = internal 

upload_protocol = usbasp

; =========================================
lib_deps =
    ; 1. Thư viện LoRa của Sandeep Mistry
    sandeepmistry/LoRa @ ^0.8.0
    
    ; 2. Thư viện cảm biến SHT31/SHT30 của Adafruit
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    
    ; (Tuỳ chọn) Đôi khi thư viện Adafruit yêu cầu thêm core BusIO
    adafruit/Adafruit BusIO @ ^1.14.1

board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xD9
board_fuses.efuse = 0xFD